version: '3'
services:
  softcar:
    image: healthcare:latest
    ports:
      - "8090:8090"
    volumes:
      - log_volume:/logs

  landoop:
    image: landoop/fast-data-dev:latest
    container_name: local-kafka
    environment:
      - "KAFKA_ADVERTISED_HOST_NAME=localhost"
      - "KAFKA_ADVERTISED_PORT=9092"
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9092:9092"
      - "9581-9585:9581-9585"
    networks:
      - legacy-handler
  splunk:
    image: splunk/splunk
    hostname: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_USER=root
      - SPLUNK_PASSWORD=legacy@007
      - SPLUNK_ENABLE_LISTEN=9997
    ports:
      - "8000:8000"
  splunkforwarder:
    image: splunk/universalforwarder:6.5.3-monitor
    hostname: splunkforwarder
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes
      - SPLUNK_FORWARD_SERVER=splunk:9997
      - SPLUNK_USER=root
      - SPLUNK_PASSWORD=legacy@007
      - SPLUNK_ADD=monitor /logs
    restart: always
    depends_on:
      - splunk
    volumes:
      - log_volume:/logs
volumes:
  log_volume: